# Generated by Django 5.2.6 on 2025-10-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_product_price_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('live', 'Live'), ('ended', 'Ended')], default='waiting', max_length=20),
        ),
    ]
