# Generated by Django 5.2.6 on 2026-03-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_timeslot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('approve', 'Approved Product'), ('reject', 'Rejected Product'), ('remove', 'Removed Product'), ('create_slot', 'Created TimeSlot'), ('pending', 'Pending Submission')], max_length=20),
        ),
    ]
